
FT_DPCM_PTR=$c000
;this file for FamiTone2 library generated by text2data tool
	.export _after_the_rain_music_data
_after_the_rain_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
; This file for the FamiTone2 library and was generated by FamiStudio


.global FAMISTUDIO_DPCM_PTR

; This file for the FamiTone2 library and was generated by FamiStudio


.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ;instrument 00 (Bass)
	.word @env4, @env1, @env1
	.byte $00
	.byte $b0 ;instrument 01 (Harpsichord-Alt1)
	.word @env14, @env1, @env1
	.byte $00
	.byte $70 ;instrument 02 (Harpsichord-Alt2)
	.word @env17, @env1, @env1
	.byte $00
	.byte $30 ;instrument 03 (Harpsichord-Intro1)
	.word @env6, @env5, @env1
	.byte $00
	.byte $70 ;instrument 04 (Harpsichord-Intro2)
	.word @env18, @env1, @env1
	.byte $00
	.byte $30 ;instrument 05 (Lead)
	.word @env11, @env1, @env8
	.byte $00
	.byte $b0 ;instrument 06 (LeadOctave)
	.word @env9, @env5, @env1
	.byte $00
	.byte $b0 ;instrument 07 (LeadOctave2)
	.word @env2, @env1, @env8
	.byte $00
	.byte $b0 ;instrument 08 (LeadPreIntro1)
	.word @env16, @env1, @env1
	.byte $00
	.byte $70 ;instrument 09 (LeadPreIntro2)
	.word @env16, @env1, @env1
	.byte $00
	.byte $30 ;instrument 0a (Snare1)
	.word @env20, @env13, @env1
	.byte $00
	.byte $30 ;instrument 0b (Snare2)
	.word @env7, @env10, @env1
	.byte $00
	.byte $70 ;instrument 0c (VoiceFadeIn)
	.word @env3, @env1, @env1
	.byte $00
	.byte $30 ;instrument 0d (VoiceFadeIn2)
	.word @env12, @env1, @env1
	.byte $00
	.byte $30 ;instrument 0e (VoiceRelease)
	.word @env15, @env1, @env1
	.byte $00
	.byte $70 ;instrument 0f (VoiceShort)
	.word @env0, @env1, @env1
	.byte $00
	.byte $30 ;instrument 10 (VoiceSoftAttack)
	.word @env19, @env1, @env8
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$0b,$0f	;1 (BassDrum)
	.byte $03+.lobyte(FT_DPCM_PTR),$17,$0e	;2 (Snare)

@env0:
	.byte $c4,$c5,$03,$c4,$00,$03
@env1:
	.byte $c0,$7f,$00,$00
@env2:
	.byte $c8,$c6,$c5,$03,$c4,$04,$c3,$c3,$c5,$c5,$c4,$c4,$c2,$00,$0c
@env3:
	.byte $c2,$03,$c3,$03,$c4,$03,$c5,$c5,$c6,$00,$08
@env4:
	.byte $cf,$7f,$00,$00
@env5:
	.byte $b4,$c0,$00,$01
@env6:
	.byte $c6,$c6,$c5,$c4,$c4,$c3,$c2,$00,$06
@env7:
	.byte $c6,$c2,$c3,$c1,$00,$03
@env8:
	.byte $c0,$0b,$c0,$c0,$c1,$c1,$c0,$c0,$bf,$bf,$00,$02
@env9:
	.byte $c8,$c8,$c6,$c5,$03,$c4,$02,$c3,$00,$07
@env10:
	.byte $c0,$c1,$c4,$00,$02
@env11:
	.byte $c4,$c5,$03,$c4,$0e,$c3,$00,$05
@env12:
	.byte $c4,$c5,$c6,$c7,$c7,$c8,$00,$05
@env13:
	.byte $c0,$c8,$ca,$cb,$ca,$cb,$cc,$ce,$00,$07
@env14:
	.byte $c7,$c6,$c5,$c5,$c4,$c4,$c3,$00,$06
@env15:
	.byte $c3,$c2,$c1,$00,$02
@env16:
	.byte $c8,$c7,$c6,$c6,$c5,$00,$04
@env17:
	.byte $c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$06
@env18:
	.byte $c6,$c5,$c4,$03,$c3,$00,$04
@env19:
	.byte $c7,$c8,$c7,$c6,$c5,$00,$04
@env20:
	.byte $ce,$c8,$c3,$c4,$c3,$c1,$00,$05
@song0ch0:
	.byte $fb, $01
@song0ref3:
	.byte $86
@song0ref4:
	.byte $46, $8b, $3c, $8b, $54, $8b, $3c, $8b
@song0ref12:
	.byte $50, $8b, $3c, $8b, $4c
@song0ref17:
	.byte $8b, $3c, $8b, $4a, $8b, $3c, $8b, $4c, $8b, $3c, $8b, $4a, $8b, $3c, $8b, $46
	.byte $ff, $0b
	.word @song0ref17
	.byte $ff, $0c
	.word @song0ref12
@song0ref39:
	.byte $42, $8b, $3c, $8b, $4a, $8b, $3c, $8b, $46, $8b, $3c, $8b
	.byte $ff, $1d
	.word @song0ref4
	.byte $ff, $0b
	.word @song0ref17
	.byte $ff, $0c
	.word @song0ref12
	.byte $ff, $0c
	.word @song0ref39
@song0ch0loop:
@song0ref64:
	.byte $8a, $4a, $99, $50, $8b, $4c, $99, $8c, $32, $8b, $2e, $8b, $32, $8b, $34, $99, $38, $99, $8e, $3c, $b5, $8a, $4a, $a7
	.byte $54, $a7, $4c, $d1, $4a, $99, $46, $99, $4a, $99, $50, $8b, $4c, $99, $8c, $38, $8b, $34, $8b, $38, $8b, $3c, $99, $3e
	.byte $99, $42, $99, $46, $99, $98, $4a, $97, $9c, $4a, $8d, $98, $4a, $a7, $9c, $4a, $99, $98, $46, $97, $9c, $46, $8d, $98
	.byte $46, $a7, $9c, $46, $99
	.byte $ff, $38
	.word @song0ref64
	.byte $9e, $44, $8f, $9c, $44, $87, $9e, $46, $8f, $9c, $46, $87, $9e, $4a, $8f, $9c, $4a, $87, $9e, $50, $8f, $9c, $50, $87
	.byte $a0, $38, $8b
@song0ref171:
	.byte $38, $8d, $9c, $38, $89, $a0, $34, $8b, $9a, $34, $99, $a0, $4c, $8b, $9a, $4c, $8b, $a0, $38, $8b, $9a
	.byte $ff, $0e
	.word @song0ref171
	.byte $ff, $0c
	.word @song0ref171
	.byte $82, $34, $8b, $4c, $8b, $32, $8b, $4a, $8b, $2e, $8b, $46, $8b, $2a, $8b, $42, $8b, $a0
@song0ref216:
	.byte $38, $8b, $38, $8b, $34, $34, $89, $4c, $4c, $c1
	.byte $ff, $0a
	.word @song0ref216
	.byte $ff, $0a
	.word @song0ref216
	.byte $90, $4c, $99, $50, $99, $4a, $8b, $4c, $a7
	.byte $ff, $1d
	.word @song0ref3
	.byte $ff, $0b
	.word @song0ref17
	.byte $ff, $0c
	.word @song0ref12
	.byte $ff, $0c
	.word @song0ref39
	.byte $ff, $1d
	.word @song0ref4
	.byte $ff, $0b
	.word @song0ref17
	.byte $ff, $0c
	.word @song0ref12
	.byte $ff, $0c
	.word @song0ref39
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ref268:
	.byte $88
@song0ref269:
	.byte $5e, $8b, $54, $8b, $6c, $8b, $54, $8b
@song0ref277:
	.byte $68, $8b, $54, $8b, $64
@song0ref282:
	.byte $8b, $54, $8b, $62, $8b, $54, $8b, $64, $8b, $54, $8b, $62, $8b, $54, $8b, $5e
	.byte $ff, $0b
	.word @song0ref282
	.byte $ff, $0c
	.word @song0ref277
@song0ref304:
	.byte $5a, $8b, $54, $8b, $62, $8b, $54, $8b, $5e, $8b, $54, $8b
	.byte $ff, $1d
	.word @song0ref269
	.byte $ff, $0b
	.word @song0ref282
	.byte $ff, $0c
	.word @song0ref277
	.byte $ff, $0c
	.word @song0ref304
@song0ch1loop:
@song0ref329:
	.byte $8a
@song0ref330:
	.byte $50, $99, $5a, $8b, $54, $f9, $81, $50, $99, $4c, $99, $50, $a7, $5a, $a7, $54, $d1, $50, $99, $4c, $99
	.byte $ff, $09
	.word @song0ref330
@song0ref354:
	.byte $54, $99, $98, $56, $97, $9c, $56, $8d, $98, $5a, $a7, $9c, $5a, $99, $98, $54, $97, $9c, $54, $8d, $98, $56, $a7, $9c
	.byte $56, $99
	.byte $ff, $15
	.word @song0ref329
	.byte $ff, $09
	.word @song0ref330
	.byte $ff, $0a
	.word @song0ref354
	.byte $9e, $54, $8f, $9c, $54, $87, $9e, $58, $8f, $9c, $58, $87, $9e, $5c, $8f, $9c, $5c, $87, $9e, $62, $8f, $9c, $62, $87
	.byte $a0, $4a, $8b
@song0ref416:
	.byte $4a, $8d, $9c, $4a, $89, $a0, $46, $8b, $9a, $46, $99, $a0, $5e, $8b, $9a, $5e, $8b, $a0, $4a, $8b, $9a
	.byte $ff, $0e
	.word @song0ref416
	.byte $ff, $0c
	.word @song0ref416
	.byte $84, $4c, $8b, $64, $8b, $4a, $8b, $62, $8b, $46, $8b, $5e, $8b, $42, $8b, $5a, $8b, $a0
@song0ref461:
	.byte $4a, $8b, $4a, $8b, $46, $46, $89, $5e, $5e, $c1
	.byte $ff, $0a
	.word @song0ref461
	.byte $ff, $0a
	.word @song0ref461
	.byte $92, $64, $99, $68, $99, $62, $8b, $64, $a7
	.byte $ff, $1d
	.word @song0ref268
	.byte $ff, $0b
	.word @song0ref282
	.byte $ff, $0c
	.word @song0ref277
	.byte $ff, $0c
	.word @song0ref304
	.byte $ff, $1d
	.word @song0ref269
	.byte $ff, $0b
	.word @song0ref282
	.byte $ff, $0c
	.word @song0ref277
	.byte $ff, $0c
	.word @song0ref304
	.byte $fd
	.word @song0ch1loop
@song0ch2:
	.byte $80
@song0ref514:
	.byte $2e, $f9, $e3, $24, $ed, $3c, $ed, $2e, $f9, $e3, $24, $ed, $3c, $ed
@song0ch2loop:
	.byte $80, $2e, $97, $00, $46, $89, $00, $2e, $8b, $00, $8b, $2e, $8b, $46, $89, $00, $8d, $2e, $97, $00, $46, $89, $00, $8d
	.byte $2e, $89, $00, $8d
@song0ref557:
	.byte $46, $89, $00, $8d, $2a, $97, $00, $42, $89, $00, $2a, $89, $00, $8d, $2a, $89, $00, $42, $8b, $00, $8b, $2a, $89, $00
	.byte $8d
@song0ref582:
	.byte $42, $89, $00, $8d, $2a, $89, $00, $2a, $89, $00, $42, $8b, $00, $8b, $26, $97, $00, $3e, $89, $00
@song0ref602:
	.byte $26, $89, $00, $8d, $26, $89, $00, $3e, $89, $00, $8d, $26, $89, $00, $26, $89, $00, $3e, $89, $00, $8d, $26, $8b, $00
	.byte $8b, $3e
@song0ref628:
	.byte $89, $00, $8d
@song0ref631:
	.byte $24, $89, $00, $24, $89, $00, $3c, $89, $00, $24, $89, $00, $8d, $24, $89, $00, $3c, $89, $00, $8d, $24, $89, $00, $8d
	.byte $3c
	.byte $ff, $0c
	.word @song0ref628
	.byte $8d, $2e, $97, $00, $46, $8b, $2e, $89, $00, $8d, $2e, $8b, $46, $89, $00, $8d, $2e, $89, $00, $2e, $89, $00, $46, $8b
	.byte $00, $8b, $2e, $8b, $00, $8b
	.byte $ff, $12
	.word @song0ref557
	.byte $89, $00, $8d, $2a, $8b, $00, $8b
	.byte $ff, $0b
	.word @song0ref582
	.byte $89, $00, $8d, $26, $97, $00, $3e, $8b
	.byte $ff, $16
	.word @song0ref602
	.byte $89, $00, $8d, $3e, $8b, $00, $8b
	.byte $ff, $0a
	.word @song0ref631
	.byte $8b, $00, $8b, $24, $89, $00, $3c, $89, $00, $8d, $24, $8b, $3c, $89, $00, $28, $89, $00, $40, $89, $00, $2c, $89, $00
	.byte $44, $89, $00, $32, $89, $00, $4a, $89, $00
@song0ref756:
	.byte $2e, $a5, $00, $2e, $a5, $00, $2e, $89, $00, $46, $8b, $2a, $a5, $00, $2a, $a5, $00, $2a, $8b, $42, $89
@song0ref777:
	.byte $00, $26, $a5, $00, $26, $a5, $00, $26, $89, $00, $3e
@song0ref788:
	.byte $89, $00, $2a, $a5, $00, $2a, $a5, $00, $2a, $89, $00, $42, $8b
	.byte $ff, $0a
	.word @song0ref756
	.byte $ff, $09
	.word @song0ref788
	.byte $97
	.byte $ff, $0e
	.word @song0ref777
	.byte $97, $00, $42, $97, $00, $2a, $89, $00, $2a, $89, $00, $42, $97, $00
	.byte $ff, $0e
	.word @song0ref514
	.byte $fd
	.word @song0ch2loop
@song0ch3:
	.byte $f9, $f9, $f9, $9b, $94, $42, $8d, $00, $a3, $f9, $f9, $f9, $9b
@song0ref844:
	.byte $42, $8d, $00, $89, $42, $89, $00, $42, $89
@song0ch3loop:
	.byte $83, $00, $97, $94
@song0ref858:
	.byte $42, $8d, $00, $a5, $42, $8d, $00, $a5, $42, $8d, $00, $a5
	.byte $ff, $0c
	.word @song0ref858
@song0ref873:
	.byte $42, $8d, $00, $a5, $42, $89, $00, $42, $89, $83, $00, $97
	.byte $ff, $0c
	.word @song0ref858
	.byte $ff, $0c
	.word @song0ref858
	.byte $ff, $0c
	.word @song0ref873
	.byte $ff, $0c
	.word @song0ref858
	.byte $ff, $0c
	.word @song0ref858
	.byte $ff, $0c
	.word @song0ref873
	.byte $ff, $0c
	.word @song0ref858
	.byte $ff, $09
	.word @song0ref858
	.byte $89, $00, $42, $8d, $00, $a5
	.byte $ff, $09
	.word @song0ref844
	.byte $00, $42, $89, $83, $00, $97
	.byte $ff, $0c
	.word @song0ref858
	.byte $42, $89, $00, $42, $8d, $00, $97
	.byte $ff, $0c
	.word @song0ref858
	.byte $42, $89, $00, $42, $89, $83, $00, $97
	.byte $ff, $0c
	.word @song0ref858
	.byte $42, $89, $00, $42, $8d, $00, $97
	.byte $ff, $09
	.word @song0ref858
	.byte $89, $00
	.byte $ff, $09
	.word @song0ref844
	.byte $00, $42, $89, $83, $00, $97
@song0ref969:
	.byte $96
@song0ref970:
	.byte $54, $85, $00, $83, $54, $85, $00, $9f, $54, $85, $00, $83, $54, $85, $00, $83, $54, $85, $00, $91
	.byte $ff, $14
	.word @song0ref970
	.byte $ff, $14
	.word @song0ref970
	.byte $54, $85, $00, $83, $54, $85, $00, $9f, $94, $42, $8d, $00, $87, $9d
	.byte $ff, $14
	.word @song0ref969
	.byte $ff, $14
	.word @song0ref970
	.byte $ff, $13
	.word @song0ref970
	.byte $ad, $94
	.byte $ff, $09
	.word @song0ref844
	.byte $fd
	.word @song0ch3loop
@song0ch4:
	.byte $02, $f9, $e3, $02, $ed, $02, $b5, $04, $b5, $02, $f9, $e3, $02, $ed, $02, $b5, $04, $99, $04, $8b, $04, $8b
@song0ch4loop:
@song0ref1050:
	.byte $02, $99, $04, $8b, $02, $99, $02, $8b, $04, $99, $02, $99, $04, $99, $02, $8b, $02, $8b, $04, $99
	.byte $ff, $13
	.word @song0ref1050
	.byte $8b, $04, $8b
	.byte $ff, $14
	.word @song0ref1050
	.byte $ff, $13
	.word @song0ref1050
	.byte $8b, $04, $8b
	.byte $ff, $14
	.word @song0ref1050
	.byte $ff, $0f
	.word @song0ref1050
	.byte $99, $04, $8b, $04, $8b
	.byte $ff, $14
	.word @song0ref1050
	.byte $ff, $09
	.word @song0ref1050
	.byte $8b, $04, $8b, $02, $99, $02, $8b, $04, $8b, $02, $8b, $04, $8b, $04, $8b, $04, $8b
	.byte $ff, $0d
	.word @song0ref1050
@song0ref1122:
	.byte $8b, $02, $99, $02, $8b, $04, $8b, $04, $8b
	.byte $ff, $0d
	.word @song0ref1050
	.byte $ff, $09
	.word @song0ref1122
	.byte $ff, $0d
	.word @song0ref1050
	.byte $ff, $09
	.word @song0ref1122
	.byte $ff, $09
	.word @song0ref1050
	.byte $ff, $09
	.word @song0ref1122
	.byte $02, $8b, $04, $8b, $04, $8b, $04, $8b, $02, $b5, $02, $ed, $02, $ed, $02, $ed, $02, $99, $04, $99, $02, $b5, $02, $ed
	.byte $02, $ed, $02, $d1, $02, $8b, $02, $8b, $04, $99, $04, $8b, $04, $8b, $fd
	.word @song0ch4loop
